version: '3.8'

services:
  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    networks:
      foodgram_network:
        ipv4_address: 172.20.0.2

  nginx:
    container_name: foodgram-proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/backend_static/
      - media:/app/media
    networks:
      foodgram_network:
        ipv4_address: 172.20.0.3

  db:
    image: postgres
    container_name: postgres_container
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      foodgram_network:
        ipv4_address: 172.20.0.4

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      foodgram_network:
        ipv4_address: 172.20.0.5

  backend_foodgram:
    container_name: backend_foodgram
    build: ../backend/
    env_file: .env
    volumes:
      - backend_static:/backend_static
      - media:/app/media
    networks:
      foodgram_network:
        ipv4_address: 172.20.0.6

volumes:
  postgres_data:
  backend_static:
  media:

networks:
  foodgram_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
