# Generated by Django 5.2.1 on 2025-06-07 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_favorite_recipe_alter_favorite_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ["-add_time"],
                "verbose_name": "Избранное пользователя",
                "verbose_name_plural": "Избранное пользователя",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ["name"],
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredientrecipe",
            options={
                "ordering": ["recipe__pub_date"],
                "verbose_name": "Ингредиенты в рецепте",
                "verbose_name_plural": "Ингредиенты в рецептах",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": ["-recipe__pub_date"],
                "verbose_name": "список покупок",
                "verbose_name_plural": "Списки покупок",
            },
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(max_length=64, verbose_name="Единица измерения"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Значение должно быть больше 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=5000, message="Максимальное значение 5000"
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                help_text="Укажите временя приготовления в минутах",
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Минимальное время приготовления 1 мин"
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=1440,
                        message="Время приготовления ограничено сутками 1440 мин",
                    ),
                ],
                verbose_name="Время приготовления в минутах",
            ),
        ),
    ]
