# Generated by Django 5.2.1 on 2025-05-30 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_shoppingcart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                help_text="Укажите временя приготовления в минутах",
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Блюдо готово!"
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=1440,
                        message="Время приготовления ограничено сутками",
                    ),
                ],
                verbose_name="Время приготовления в минутах",
            ),
        ),
    ]
