# Generated by Django 5.2.1 on 2025-06-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_shoppingcart_recipe_alter_shoppingcart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_favorites",
                to="recipes.recipe",
                verbose_name="Рецепт в избранном пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_shopping_carts",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
    ]
