# Generated by Django 5.2.1 on 2025-06-07 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_subscription_subscribed_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscribed_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписан на",
            ),
        ),
    ]
