# Generated by Django 5.2.1 on 2025-06-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_subscription_subscribed_to"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["subscribed_to__username"],
                "verbose_name": "Подписчик",
                "verbose_name_plural": "Подписчики",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["username"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
